In [1]:
struct ChessBoard
    board::Matrix
end

In [2]:
A=[1 2 3;
4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [3]:
cb=ChessBoard(A)

ChessBoard([1 2 3; 4 5 6])

In [4]:
cb.board

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [5]:
B=trues(8,8)

8×8 BitArray{2}:
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true
 true  true  true  true  true  true  true  true

In [12]:
mutable struct ChessBoard2
    board::Matrix
end

In [13]:
cb2=ChessBoard(A)

ChessBoard([1 2 3; 4 5 6])

In [14]:
cb2.board=B

LoadError: type ChessBoard is immutable

In [15]:
struct ChessBoard
    board::Matrix

    ChessBoard(m,n)=new(trues(m,n))
end

In [18]:
struct ChessBoard3{T}
    board::Matrix{T}
    ChessBoard3{T}(m,n)where T=new(zeros(T,m,n))
end

LoadError: syntax: extra token "T" after end of expression

In [19]:
struct ChessBoard4
    board::Matrix{Bool}
    ChessBoard4(n)=new(trues(n,n))
end

In [20]:
check(cb::ChessBoard4,x,y)=cb.board[x,y]

check (generic function with 1 method)

In [21]:
function place!(cb::ChessBoard4,x,y)
    cb.board[x,:]=false
    cb.board[:,y]=false
    cb
end

place! (generic function with 1 method)

In [22]:
cb=ChessBoard4(8)

ChessBoard4(Bool[true true … true true; true true … true true; … ; true true … true true; true true … true true])

In [23]:
place!(cb,3,4)

ChessBoard4(Bool[true true … true true; true true … true true; … ; true true … true true; true true … true true])

In [25]:
cb.board

8×8 Array{Bool,2}:
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
 false  false  false  false  false  false  false  false
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true
  true   true   true  false   true   true   true   true